/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as AdminSurveysRouteImport } from './routes/admin.surveys'
import { Route as AdminResponsesRouteImport } from './routes/admin.responses'
import { Route as AdminNewRouteImport } from './routes/admin.new'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminSurveysIndexRouteImport } from './routes/admin.surveys.index'
import { Route as AdminSurveysIdRouteImport } from './routes/admin.surveys.$id'
import { Route as AdminCustomersIdRouteImport } from './routes/admin.customers.$id'
import { Route as AdminSurveysIdResultRouteImport } from './routes/admin.surveys.$id.result'
import { Route as AdminSurveysIdPublishRouteImport } from './routes/admin.surveys.$id.publish'
import { Route as AdminSurveysIdEditRouteImport } from './routes/admin.surveys.$id.edit'
import { Route as AdminSurveysIdAnalyticsRouteImport } from './routes/admin.surveys.$id.analytics'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSurveysRoute = AdminSurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResponsesRoute = AdminResponsesRouteImport.update({
  id: '/responses',
  path: '/responses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSurveysIndexRoute = AdminSurveysIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSurveysRoute,
} as any)
const AdminSurveysIdRoute = AdminSurveysIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminSurveysRoute,
} as any)
const AdminCustomersIdRoute = AdminCustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCustomersRoute,
} as any)
const AdminSurveysIdResultRoute = AdminSurveysIdResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => AdminSurveysIdRoute,
} as any)
const AdminSurveysIdPublishRoute = AdminSurveysIdPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => AdminSurveysIdRoute,
} as any)
const AdminSurveysIdEditRoute = AdminSurveysIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminSurveysIdRoute,
} as any)
const AdminSurveysIdAnalyticsRoute = AdminSurveysIdAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminSurveysIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/new': typeof AdminNewRoute
  '/admin/responses': typeof AdminResponsesRoute
  '/admin/surveys': typeof AdminSurveysRouteWithChildren
  '/s/$slug': typeof SSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/surveys/$id': typeof AdminSurveysIdRouteWithChildren
  '/admin/surveys/': typeof AdminSurveysIndexRoute
  '/admin/surveys/$id/analytics': typeof AdminSurveysIdAnalyticsRoute
  '/admin/surveys/$id/edit': typeof AdminSurveysIdEditRoute
  '/admin/surveys/$id/publish': typeof AdminSurveysIdPublishRoute
  '/admin/surveys/$id/result': typeof AdminSurveysIdResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/new': typeof AdminNewRoute
  '/admin/responses': typeof AdminResponsesRoute
  '/s/$slug': typeof SSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/surveys/$id': typeof AdminSurveysIdRouteWithChildren
  '/admin/surveys': typeof AdminSurveysIndexRoute
  '/admin/surveys/$id/analytics': typeof AdminSurveysIdAnalyticsRoute
  '/admin/surveys/$id/edit': typeof AdminSurveysIdEditRoute
  '/admin/surveys/$id/publish': typeof AdminSurveysIdPublishRoute
  '/admin/surveys/$id/result': typeof AdminSurveysIdResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/new': typeof AdminNewRoute
  '/admin/responses': typeof AdminResponsesRoute
  '/admin/surveys': typeof AdminSurveysRouteWithChildren
  '/s/$slug': typeof SSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/surveys/$id': typeof AdminSurveysIdRouteWithChildren
  '/admin/surveys/': typeof AdminSurveysIndexRoute
  '/admin/surveys/$id/analytics': typeof AdminSurveysIdAnalyticsRoute
  '/admin/surveys/$id/edit': typeof AdminSurveysIdEditRoute
  '/admin/surveys/$id/publish': typeof AdminSurveysIdPublishRoute
  '/admin/surveys/$id/result': typeof AdminSurveysIdResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/customers'
    | '/admin/new'
    | '/admin/responses'
    | '/admin/surveys'
    | '/s/$slug'
    | '/admin/'
    | '/admin/customers/$id'
    | '/admin/surveys/$id'
    | '/admin/surveys/'
    | '/admin/surveys/$id/analytics'
    | '/admin/surveys/$id/edit'
    | '/admin/surveys/$id/publish'
    | '/admin/surveys/$id/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/customers'
    | '/admin/new'
    | '/admin/responses'
    | '/s/$slug'
    | '/admin'
    | '/admin/customers/$id'
    | '/admin/surveys/$id'
    | '/admin/surveys'
    | '/admin/surveys/$id/analytics'
    | '/admin/surveys/$id/edit'
    | '/admin/surveys/$id/publish'
    | '/admin/surveys/$id/result'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/customers'
    | '/admin/new'
    | '/admin/responses'
    | '/admin/surveys'
    | '/s/$slug'
    | '/admin/'
    | '/admin/customers/$id'
    | '/admin/surveys/$id'
    | '/admin/surveys/'
    | '/admin/surveys/$id/analytics'
    | '/admin/surveys/$id/edit'
    | '/admin/surveys/$id/publish'
    | '/admin/surveys/$id/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  SSlugRoute: typeof SSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/surveys': {
      id: '/admin/surveys'
      path: '/surveys'
      fullPath: '/admin/surveys'
      preLoaderRoute: typeof AdminSurveysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/responses': {
      id: '/admin/responses'
      path: '/responses'
      fullPath: '/admin/responses'
      preLoaderRoute: typeof AdminResponsesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/surveys/': {
      id: '/admin/surveys/'
      path: '/'
      fullPath: '/admin/surveys/'
      preLoaderRoute: typeof AdminSurveysIndexRouteImport
      parentRoute: typeof AdminSurveysRoute
    }
    '/admin/surveys/$id': {
      id: '/admin/surveys/$id'
      path: '/$id'
      fullPath: '/admin/surveys/$id'
      preLoaderRoute: typeof AdminSurveysIdRouteImport
      parentRoute: typeof AdminSurveysRoute
    }
    '/admin/customers/$id': {
      id: '/admin/customers/$id'
      path: '/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AdminCustomersIdRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/surveys/$id/result': {
      id: '/admin/surveys/$id/result'
      path: '/result'
      fullPath: '/admin/surveys/$id/result'
      preLoaderRoute: typeof AdminSurveysIdResultRouteImport
      parentRoute: typeof AdminSurveysIdRoute
    }
    '/admin/surveys/$id/publish': {
      id: '/admin/surveys/$id/publish'
      path: '/publish'
      fullPath: '/admin/surveys/$id/publish'
      preLoaderRoute: typeof AdminSurveysIdPublishRouteImport
      parentRoute: typeof AdminSurveysIdRoute
    }
    '/admin/surveys/$id/edit': {
      id: '/admin/surveys/$id/edit'
      path: '/edit'
      fullPath: '/admin/surveys/$id/edit'
      preLoaderRoute: typeof AdminSurveysIdEditRouteImport
      parentRoute: typeof AdminSurveysIdRoute
    }
    '/admin/surveys/$id/analytics': {
      id: '/admin/surveys/$id/analytics'
      path: '/analytics'
      fullPath: '/admin/surveys/$id/analytics'
      preLoaderRoute: typeof AdminSurveysIdAnalyticsRouteImport
      parentRoute: typeof AdminSurveysIdRoute
    }
  }
}

interface AdminCustomersRouteChildren {
  AdminCustomersIdRoute: typeof AdminCustomersIdRoute
}

const AdminCustomersRouteChildren: AdminCustomersRouteChildren = {
  AdminCustomersIdRoute: AdminCustomersIdRoute,
}

const AdminCustomersRouteWithChildren = AdminCustomersRoute._addFileChildren(
  AdminCustomersRouteChildren,
)

interface AdminSurveysIdRouteChildren {
  AdminSurveysIdAnalyticsRoute: typeof AdminSurveysIdAnalyticsRoute
  AdminSurveysIdEditRoute: typeof AdminSurveysIdEditRoute
  AdminSurveysIdPublishRoute: typeof AdminSurveysIdPublishRoute
  AdminSurveysIdResultRoute: typeof AdminSurveysIdResultRoute
}

const AdminSurveysIdRouteChildren: AdminSurveysIdRouteChildren = {
  AdminSurveysIdAnalyticsRoute: AdminSurveysIdAnalyticsRoute,
  AdminSurveysIdEditRoute: AdminSurveysIdEditRoute,
  AdminSurveysIdPublishRoute: AdminSurveysIdPublishRoute,
  AdminSurveysIdResultRoute: AdminSurveysIdResultRoute,
}

const AdminSurveysIdRouteWithChildren = AdminSurveysIdRoute._addFileChildren(
  AdminSurveysIdRouteChildren,
)

interface AdminSurveysRouteChildren {
  AdminSurveysIdRoute: typeof AdminSurveysIdRouteWithChildren
  AdminSurveysIndexRoute: typeof AdminSurveysIndexRoute
}

const AdminSurveysRouteChildren: AdminSurveysRouteChildren = {
  AdminSurveysIdRoute: AdminSurveysIdRouteWithChildren,
  AdminSurveysIndexRoute: AdminSurveysIndexRoute,
}

const AdminSurveysRouteWithChildren = AdminSurveysRoute._addFileChildren(
  AdminSurveysRouteChildren,
)

interface AdminRouteChildren {
  AdminCustomersRoute: typeof AdminCustomersRouteWithChildren
  AdminNewRoute: typeof AdminNewRoute
  AdminResponsesRoute: typeof AdminResponsesRoute
  AdminSurveysRoute: typeof AdminSurveysRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCustomersRoute: AdminCustomersRouteWithChildren,
  AdminNewRoute: AdminNewRoute,
  AdminResponsesRoute: AdminResponsesRoute,
  AdminSurveysRoute: AdminSurveysRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  SSlugRoute: SSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
